version: '3'

services:
  redis:
    image: redis:alpine
    command: --save 900 1
    volumes:
      - ./data/redis:/data
    restart: on-failure:5
    network_mode: "host"
  ntopng:
    build:
      context: ntop
      dockerfile: Dockerfile
    command: ntopng -r localhost:6379 -d /ntopngcustom
    volumes:
      - ./data/ntopng:/var/lib/ntopng
    restart: on-failure:5
    network_mode: "host"
    depends_on:
      - redis